[cloud]
cloud_annotation_get_folder = "D:\\Users\\maxwelfreitas\\ANATEL\\InovaFiscaliza - DataHub - GET\\SCH"
cloud_annotation_post_folder = "D:\\Users\\maxwelfreitas\\ANATEL\\InovaFiscaliza - DataHub - POST\\SCH"

[credentials]
creds_file = "D:\\Users\\maxwelfreitas\\OneDrive - ANATEL\\creds.ini"